In [1]:
import numpy as np


In [9]:
file = open("test/tree3/tree3_box_10_32_pattern_1.txt", 'r')

size = file.readline(0)
voxels = file.readlines()[1].split(",")

size = 32
print(size)
# print(voxels)

32


In [3]:
# print(size)

In [10]:
# print(size)
vox_np = []
for vox in voxels:
    # print(i, vox)
    if(vox== '0'):
        vox_np.append(0)
    elif(vox=='1'):
        vox_np.append(1)
    else:
        print(vox)
    # vox_np.append(int(vox))
vox_np = np.array(vox_np, dtype=np.uint8)
print(len(vox_np))
vox_np = np.reshape(vox_np, (size,size,size))
print(vox_np)



32768
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 0 1 1]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 1 1 1]
  [0 0 0 ... 0 0 1]]]


In [16]:
import matplotlib.pyplot as plt
fig = plt.figure()
# ax = fig.gca?
ax = fig.add_subplot(111, projection="3d")
# ax.voxels(vox_np, facecolors='red', edgecolor='k')
plt.show()

ValueError: Unknown projection '3d'